### PR TITLE
Add Issue and PR templates.

### PR DESCRIPTION
**Pull request by l-zeuch**
This pull request adds GitHub issue and PR templates.

These templates will allow for a more concise and thorough workflow.
Just a further step to organize the repository before going into the "real coding".

Thanks : )

### CODE REVIEW

**Review by Goldscar1 — CHANGES_REQUESTED** [review]
Ein paar grammatische Fehler sind noch zu korrigieren, wenn das erledigt ist, kann approved werden

**Review by Goldscar1 — APPROVED** [review]
Soweit halte ich die PR für Merge-bereit

**Comment by l-zeuch** [comment]
I pushed a few more fixes, general wording and grammar.
Once the check has passed we are ready for merge.

**Review by Goldscar1 — APPROVED** [review]

**Comment by l-zeuch** [comment]
Thanks, I'll now merge!

**Pull request merged**
